version: '3.9'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: atcoder
    volumes:
      - ./:/home/app
      - node_modules_volume:/home/app/node_modules:delegated

volumes:
  node_modules_volume:
